---
- name: package installer - template
  hosts: all
  become_user: root
  become: true
  vars:
    preinst_packages:
      - ksh
      - make
      - sysstat
      - java
    pState: present
#           present - install/verify install
#           latest - upgrade to latest version
#           absent - remove
  tasks:
    - name: install listed packages
      yum: 
        name: "{{ preinst_packages }}"
        state: "{{pState}}"
    

