---
- name: update_password.yml - linux password reset 
# call with: --extra-vars newpassword=12345678
#            --limit=db2
#            ansible-playbook -i update_password.yml --extra-vars newpassword=changeM3 --limit=db2 -K
  hosts: all
  become: yes
  tasks:
    - name: Change user password
      user:
        name: oracle
        update_password: always
        password: "{{ newpassword|password_hash('sha512') }}"
